sudo: required
services:
  - docker

before_install:
  - docker build -t hongaponga/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hongaponga/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ca-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ca-central-1-559022758883"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  access_secret_key: "$AWS_SECRET_KEY"
